const create_error=(res,req,next)=>{
next(createError(404,'Not found'))
}
module.exports=create_error;